print("Hello \"world\" world")
print('I\'m Amisha!')
print("line A")
print("line B")
print("line A\nline B")
print("name\tAmisha")
print("this is \ backslash")
print("this is backslash\\")
print("this is backslash\\\\")
print("this is backslash\\\\\\\\")
print("Helll\bo")